### ISSUE TITLE
khan academy and neurips datasets are not downloading correctly

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/data-wrangler#22]
example (downloading neurips dataset):

<img width="973" alt="Screen Shot 2021-08-03 at 9 52 25 AM" src="https://user-images.githubusercontent.com/9030494/128027734-514b80bf-f6f7-461b-8a5e-dd2621c4497b.png">

i'm thinking one of the following may have happened:
- the download links are broken
- the "load" function is broken for remote downloads of npy/npz files
- something about my local cache is messed up (e.g. interrupted download)-- 

it's surprising that the tests using minipedia and sotus datasets would have passed on the CI system if `load` was truly broken, which makes me think it may be a local issue...but it needs to be debugged further.

**Comment by paxtonfitzpatrick** [comment]
It looks like the problem is the dropbox URLs for the neurips and khan academy datasets point to deleted files (maybe they were re-uploaded at some point and not updated in the code?).

The `invalid load key, '<'` error happens because dropbox displays a 404 page for bad direct-download links, so the data from the `requests.Response` object that gets saved to the local file is the HTML content for that page, rather than the pickled object:

![Screen Shot 2021-08-04 at 4 30 56 AM](https://user-images.githubusercontent.com/26118297/128149045-55ad685d-5172-4ea2-a164-06ec3be2e730.png)
(**Note**: `datawrangler.io.io.get_local_fname()` should probably strip the `?dl=1` suffix from the URL when creating the local filename)

Then, when trying to unpickle the file (via `np.load(<fpath>, allow_pickle=True)`), the `pickle` module throws an error because the first character it encounters in the HTML content ("`<`") is not a valid pickle opcode:

https://github.com/python/cpython/blob/ac811f9b5a68ce8756911ef2c8be83b46696018f/Modules/_pickle.c#L6946-L6960
```c
default:
    {
        PickleState *st = _Pickle_GetGlobalState();
        unsigned char c = (unsigned char) *s;
        if (0x20 <= c && c <= 0x7e && c != '\'' && c != '\\') {
            PyErr_Format(st->UnpicklingError,
                         "invalid load key, '%c'.", c);
        }
        else {
            PyErr_Format(st->UnpicklingError,
                         "invalid load key, '\\x%02x'.", c);
        }
        return NULL;
    }
}
```


Opening the neurips or khan academy dataset links without the direct-download extension results in this page:
![Screen Shot 2021-08-04 at 5 05 12 AM](https://user-images.githubusercontent.com/26118297/128154100-afe288ea-7165-495d-ae6a-31748085dc28.png)

**Comment by jeremymanning** [comment]
Fixed...
